#!/bin/bash

set -e
source "$(dirname "$(readlink -f "$0")")/dxp.config"

dxp-test-setup

keytool -genkey -v -keystore keystore -storepass android -alias key -keypass android -keyalg RSA -keysize 2048 -validity 36500

