#!/bin/bash

set -e
source "$(dirname "$(readlink -f "$0")")/dxp.config"

if [ ! -d decode ]; then
    echo "error: please run this command from the root directory of a structure built by 'dxp-setup-for-apk'"
    exit 1
fi

keytool -genkey -v -keystore keystore -storepass android -alias key -keypass android -keyalg RSA -keysize 2048 -validity 36500

